name: geoapps_ga

channels:
  - conda-forge
dependencies:
  - python
  - pip
  - git
  - conda-forge::discretize==0.7.4
  - numpy
  - scipy
  - matplotlib
  - zarr
  - fsspec
  - h5py
  - requests
  - empymod
  - pydiso
  - setuptools
  - mkl
  - pyyaml
  - properties
  - scikit-learn
  - pymatsolver
variables:
  KMP_WARNINGS: 0
