name: Create JIRA issue
permissions:
  contents: read
  issues: write

on:
  issues:
    types: [opened]

jobs:
  call-workflow-create-jira-issue:
    if: github.event.pull_request.head.repo.full_name == 'MiraGeoscience/geoapps'  # do not run on repository forks
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-jira-issue_to_jira.yml@main
    secrets:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
      JIRA_URL: ${{ secrets.JIRA_URL }}
    with:
      project-key: 'GEOPY'
      components: '[{"name": "geoapps"}]'
