name: Create JIRA issue

on:
  issues:
    types: [opened]

jobs:
  call-workflow-create-jira-issue:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-jira-issue_to_jira.yml@DEVOPS-466
    secrets: inherit
    with:
      project-key: 'GEOPY'
