name: Python analysis

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-workflow-static-analysis:
    name: Static analysis
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-static_analysis.yml@main
    with:
      package-manager: 'conda'
      app-name: 'geoapps'
      python-version: '3.10'
  call-workflow-pytest:
    name: Pytest
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-pytest.yml@main
    with:
      package-manager: 'conda'
      python-versions: '["3.10"]'
      os: '["ubuntu-latest", "windows-latest"]'
      cache-number: 1
      codecov-reference-python-version: '3.10'
      codecov-reference-os: '["windows-latest"]'
      lfs: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
