name: Python analysis

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
      - DEVOPS-471 # TODO: Temporary until DEVOPS-471 is merged

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-workflow-static-analysis:
    name: Static analysis
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-static_analysis.yml@DEVOPS-466
    with:
      package-manager: 'conda'
      app-name: 'geoapps'
      python-version: '3.10'
  call-workflow-pytest-on-windows:
    name: Pytest on Windows
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-pytest_windows.yml@DEVOPS-471
    with:
      package-manager: 'conda'
      python-versions: '["3.10"]'
      cache-number: 1
      codecov-reference-python-version: '3.10'
      lfs: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  call-workflow-pytest-on-unix-os:
    name: Pytest on Unix OS
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-pytest_unix_os.yml@DEVOPS-471
    with:
      package-manager: 'conda'
      python-versions: '["3.10"]'
      os: '["ubuntu-latest"]'
      cache-number: 1
      lfs: true
